### ISSUE TITLE
Can't link project (connect: no route to host)

### ISSUE THREAD

**Issue by falconmasters** [supabase/cli#1996]
**Describe the bug**
I get the following error trying to link to the project using `supabase link`
```Retrying... db.redacted.supabase.co 5432
failed to connect to `host=db.redacted.supabase.co user=postgres database=postgres`: dial error (dial tcp [2600:1f1c:f9:4d0a:8d82:ad21:9ea8:8fd9]:5432: connect: no route to host)
Try rerunning the command with --debug to troubleshoot the error.```

I have tried to execute some other commands like pull and push using the --db-url flag but I get a similar error.

I noticed that on my dashboard some times I get an ip banned, I guess it's mine, I unban it but the problem persists.

**To Reproduce**
Steps to reproduce the behavior:
1. Download supabase cli
2. Execute supabase link
3. Select a project
4. Type the password
5. Get the error

**Expected behavior**
Should be able to link the project or get a more concise description of what the problem is.

**System information**
 - OS: MAC OS
 - Version of CLI: 1.123.4

**Additional context**
 - Version of Node.js: 20.8.1

**Comment by falconmasters** [comment]
I just realized that I have supabase globally instaled on my computer so I never type the npx prefix to the commands. 
I tried executing the commands adding the prefix. i.e
`npx supabase link`

And now I don't get the connection error.

**Comment by Jaszkowic** [comment]
I had the same problem with supabase `v1.120.0`: `npx supabase link --project-ref XXX --password YYY` tried to connect to `db.XXX.supabase.co` with error:

> failed to connect to `host=db.XXX.supabase.co user=postgres database=postgres`: dial error (dial tcp [...]:5432: connect: no route to host)
Try rerunning the command with --debug to troubleshoot the error.

although connection pooling is enabled and host should be `aws-0-eu-central-1.pooler.supabase.com` 

**After upgrading Supabase to `v1.145.4`, the linking worked properly.**

**Comment by sweatybridge** [comment]
Thanks for the update. I will close this issue since it seems resolved.

**Comment by acomms** [comment]
Since this shows up high in Google: I had a "no route to host" error be related to the switch to ipv6. My fix was related to my home network router settings. More help related to this and ipv6 changeover: https://github.com/orgs/supabase/discussions/17817

**Comment by Seanmclem** [comment]
> Since this shows up high in Google: I had a "no route to host" error be related to the switch to ipv6. My fix was related to my home network router settings. More help related to this and ipv6 changeover: https://github.com/orgs/supabase/discussions/17817

So like, my local network needs to use IPV6 for local addresses? I think my network is like a hybrid. Like most routers from the past 5-10 years. Idk what to do

**Comment by sweatybridge** [comment]
> So like, my local network needs to use IPV6 for local addresses?

You only need IPv6 on home router when connecting directly to hosted db. Connecting to the connection pooler still works over IPv4. 

If you are having trouble linking, try deleting `supabase/.temp` before `supabase link`.

**Comment by landsman** [comment]
> If you are having trouble linking, try deleting supabase/.temp before supabase link.

This! It should be part of the error as a suggestion!

**Comment by SayedShahidi** [comment]
Still having issues with this. Out of nowhere and none of these work, not on my machine nor of that of my team.

**Comment by kaytladi22** [comment]
> Still having issues with this. Out of nowhere and none of these work, not on my machine nor of that of my team.

Have you found an alternate source of info for this issue. Currently experiencing it.

**Comment by sbushell92** [comment]
I am also currently experiencing this today.

**Comment by etzelc** [comment]
We first experienced the same on our Bitbucket Cloud runners, but since some minutes it changed to this error: https://github.com/supabase/cli/issues/1224
Maybe because of the incident: https://status.supabase.com/incidents/3h1gjkvf7dmd

**Comment by etzelc** [comment]
Is fixed for us.

**Comment by kaytladi22** [comment]
I was able to fix this by 

1) resetting the DB password from the dashboard

2) having in my env :

 ```
NX_PUBLIC_SUPABASE_URL=https://XXX.supabase.co
NX_PUBLIC_SUPABASE_ANON_KEY=anon key
NX_PUBLIC_ONE_UP_DATABASE_URL=postgresql://postgres.[PROJECT REF]:[DATABASE-PASSWORD]@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
```

3) Using supabase login to login in via browser
4) Using  supabase link --project-ref [PROJECT REF] --debug. (recommend using debug to see exactly whats failing this is how I saw it was the db)
5) Slapping in the password on prompt 

As for the IPV4 vs IPV6 stuff it turns out my home network uses both and since I recently created the Supabase project so I think all the newest projects have [https://github.com/orgs/supabase/discussions/17817](url) Supavisor connection pooler automatically enabled I opted to use the Transactional Pooler just to be safe.

**Comment by groksrc** [comment]
I am experiencing this today from GitHub actions as well.

**Comment by ekediala** [comment]
Still having these issues @sweatybridge 

OS: macOS 15.3.2
Command: npx supabase link --create-ticket
Response: failed to connect to postgres: failed to connect to `host=aws-0-eu-central-1.pooler.supabase.com user=postgres.xxxx database=postgres`: failed SASL auth (invalid SCRAM server-final-message received from server)

**Comment by Marviel** [comment]
Still having this issue as well -- 

failed to connect to postgres: failed to connect to `host=db.[DATABASE_ID].supabase.co user=... database=...`

**Comment by groksrc** [comment]
FYI for anyone having this issue with GitHub Actions, you can fix it by forcing the `supabase/setup-cli` to use a working version.

https://github.com/supabase/setup-cli/issues/323

**Comment by AronAsmundsson** [comment]
The solution we that worked for us was updating the CLI, deleting the .temp and config, stopping the database, and then doing innit and then linking to the DB.

It appears that the issue is a combination of config.toml, .temp, and an outdated CLI.
