### ISSUE TITLE
Privileges revoked from all storage tables after pull of storage schema (db pull --schema storage)

### ISSUE THREAD

**Issue by PatoSala** [supabase/cli#4107]
**Describe the bug**
When using supabase db pull --schema storage the migration file contains lots of revoke statements that remove all privileges of all storage stables from all database users (anon, authenticated, service_role, etc...)

**To Reproduce**
Steps to reproduce the behavior (keep in mind storage schema must have buckets created with RLS policies, it's not a blank storage):
1. supabase init
2. supabase login
3. supabase link $PROJECT_REF
4. supabase start
5. supabase db pull
6. supabase db pull --schema storage
7. supabase db reset

This threw an Error status 400 because the newly created migration file when storage was pulled generated all the following revoke statements around the storage schema:

<img width="1734" height="136" alt="Image" src="https://github.com/user-attachments/assets/00fe82b8-51e6-4290-8619-6b8a7585f435" />

[message.txt](https://github.com/user-attachments/files/22095258/message.txt)

 The migration file first generates the revoke statements and the proceeds into the creation of the storage schema with all of its policies, triggers, etc. I only uploaded the revoke statements.

**Expected behavior**
A working storage schema just as the one in the hosted project.

**System information**
 - Version of OS: macOS Sequoia (Intel)
 - Version of CLI: 2.34.3
 - Version of Docker: 4.43.2 
 - Versions of services
   
   SERVICE IMAGE                   | LOCAL                  | LINKED     
  ----------------------------|---------------------------|------------
   supabase/postgres               | 15.8.1.054                          | 15.8.1.054 
   supabase/gotrue                  | v2.178.0                              | v2.179.0   
   postgrest/postgrest             | v12.2.3                                 | v12.2.3    
   supabase/realtime               | v2.41.23                               | -          
   supabase/storage-api         | v1.26.3                                 | -          
   supabase/edge-runtime      | v1.68.3                                 | -          
   supabase/studio                  | 2025.08.04-sha-6e99ca6 | -          
   supabase/postgres-meta    | v0.91.5                                 | -          
   supabase/logflare                 | 1.18.3                                   | -          
   supabase/supavisor              | 2.6.1                                    | -          

**Update:**
I created another local instance and now the revoke statements where created also for the auth schema
The process was quiet simple and even like that the revoke statements where generated:

```zsh
supabase init
supabase login
supabase link
supabase db pull --linked
supabase db pull --linked --schema auth
supabase db pull --linked --schema storage
```

The generated revoke statements are the following:

[auth-revokes.txt](https://github.com/user-attachments/files/22189077/auth-revokes.txt)

[storage-revokes.txt](https://github.com/user-attachments/files/22189082/storage-revokes.txt)

**UPDATE 2**: Just compared both auth and storage revokes and auth only revokes permissions from "dashboard_user" and "postgres" while storage revokes permissions from:
authenticated
service_role
anon
postgres

After testing, auth schema seems to work ok (even though I don't know if does revokes should be generated) but storage is not even able to connect through supabase studio. I attached an image showing the studio error and the generated migration file for storage schema.

<img width="719" height="196" alt="Image" src="https://github.com/user-attachments/assets/ae5b69da-e23a-4fc3-9cec-662cd41ab1fd" />

**Comment by PatoSala** [comment]
By manually removing all the revoke statements storage works correctly, but it's not the intended behaviour.

**Comment by piersonmarks** [comment]
+1 - been pulling my hair out all day on this

**Comment by sweatybridge** [comment]
This should be fixed in cli beta release.

```bash
npx supabase@beta db pull --schema auth,storage
```

We now only diff triggers and RLS policies in managed schemas.

**Comment by PatoSala** [comment]
@sweatybridge I created a new local project to start from zero using the beta version. When I ran `npx supabase@beta db pull` it also pulled auth and storage schemas rls policies, triggers and functions without specifying `--schema auth,storage`. Is that the intented behavior in this cli version? I don't mind this behaviour, but just to clarify since the docs say that those schemas should be pulled apart.

**Comment by sweatybridge** [comment]
> Is that the intented behavior in this cli version?

Yup, that's indeed an intentional change I introduced. I will update the docs accordingly next week, before the release to stable channel.

**Comment by PatoSala** [comment]
I really like this change. Thanks!

**Comment by amirnksb** [comment]
@sweatybridge still getting revoke statements even after using npx supabase@beta db pull, really confused. Even after starting a fresh local supabase cli

**Comment by anmolsood21** [comment]
@sweatybridge  +1 - Without proper documentation, this is leading to a lot of issues while syncing schemas. Would love to get some guidance here on what's going on.

**Comment by PatoSala** [comment]
@anmolsood21 can you better detail your problem? Maybe I can help you. What are you trying to do? In which schema are the revoke statements being generated? If possible attach the migration file.

**Comment by bobbybol** [comment]
> This should be fixed in cli beta release.
> 
> npx supabase@beta db pull --schema auth,storage
> We now only diff triggers and RLS policies in managed schemas.

Is this why I now get a 3500 line migration file on `supabase db pull`? (When I revert to v2.41.3 I have no changes, as expected).

**Comment by nicksergeant** [comment]
Hi! I'm running into this as well, but when I try to use the `@beta`:

```
❯ npx supabase@beta db pull --schema auth,storage
Initialising login role...
Connecting to remote database...
Creating shadow database...
Initialising schema...
Seeding globals from roles.sql...
Applying migration 20251024132041_remote_schema.sql...
Diffing schemas: auth,storage
error diffing schema: error running container: exit 1:
[sql_e12dd29]: Executing query failed: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
main worker has been destroyed

Try rerunning the command with --debug to troubleshoot the error.
```

This seems to be reproducible every time. Running without `@beta` resolves the SASL issue but then generates the huge priv revocations migration...

**Comment by PatoSala** [comment]
> Hi! I'm running into this as well, but when I try to use the `@beta`:
> 
> ```
> ❯ npx supabase@beta db pull --schema auth,storage
> Initialising login role...
> Connecting to remote database...
> Creating shadow database...
> Initialising schema...
> Seeding globals from roles.sql...
> Applying migration 20251024132041_remote_schema.sql...
> Diffing schemas: auth,storage
> error diffing schema: error running container: exit 1:
> [sql_e12dd29]: Executing query failed: SASL: SCRAM-SERVER-FINAL-MESSAGE: server signature is missing
> main worker has been destroyed
> 
> Try rerunning the command with --debug to troubleshoot the error.
> ```
> 
> This seems to be reproducible every time. Running without `@beta` resolves the SASL issue but then generates the huge priv revocations migration...

Lately there's been a lot of reports on this revoke statements problem. Personally for me the beta version that @sweatybridge released a few weeks ago worked for me but it seems that it didn't worked for lots of other people. I've been off from building with supabase for the past few weeks because I'm into other projects so I can't confirm if this issue is still happening to me, but the last time I used it it worked. As soon as I finish with this other project I'll return to supabase and check if this issue is happening again. Maybe you should check this other open issue which is related and it's where people are reporting the revoke statements problem:
https://github.com/supabase/cli/issues/4068

**Comment by Almopt** [comment]
@sweatybridge I'm still getting the revokes.
